```{r}
library(tidyverse)
library(readxl)
library(lubridate)
```

```{r}
DATA_PATH <- "/Users/Usuario/Desktop/Help ME"
setwd(DATA_PATH)

```

```{r}
SALES_DATA <- 'sales.csv'
sales <- read.csv2(SALES_DATA, sep=";", header=T)
```

```{r}
STORES_INFO_DATA <- 'stores_info.xlsx'
stores <- read_excel(STORES_INFO_DATA, sheet = "data")
```

```{r}
sales_all <- sales %>% left_join(stores, by=c("store"))

```

```{r}
sales_all$date <- ymd(sales_all$date)
```

```{r}
sales_all <- sales_all %>% 
  mutate(year = year(date), month = month(date)) %>% 
  filter(year >= 2013 & year <= 2015)

```

```{r}
monthly_sales <- sales_all %>%
  group_by(country, year, month) %>%
  summarise(total_sales = sum(sales), .groups = 'drop')
```

```{r}
monthly_sales <- monthly_sales %>%
  arrange(country, year, month) %>%
  group_by(country) %>%
  mutate(prev_month_sales = lag(total_sales),
         pct_change = (total_sales - prev_month_sales) / prev_month_sales * 100) %>%
  ungroup() %>%
  select(country, year, month, pct_change)

```

```{r}
print(monthly_sales)

```

```{r}
write.csv(monthly_sales, "prop_changes_sales_by_country_by_year_month.csv", row.names = FALSE)

```

```{r}
cat("La tabla 'prop_changes_sales_by_country_by_year_month.csv' ha sido creada exitosamente.\n")

```
